version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: library
      POSTGRES_PASSWORD: library
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://library:library@db:5432/library_db
    ports:
      - "8000:8000"
